/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppInspirationRouteImport } from './routes/_app.inspiration'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppComposeRouteImport } from './routes/_app.compose'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppFeedIndexRouteImport } from './routes/_app.feed.index'
import { Route as AppFeedStoryIdRouteImport } from './routes/_app.feed.$storyId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInspirationRoute = AppInspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppComposeRoute = AppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedIndexRoute = AppFeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFeedRoute,
} as any)
const AppFeedStoryIdRoute = AppFeedStoryIdRouteImport.update({
  id: '/$storyId',
  path: '/$storyId',
  getParentRoute: () => AppFeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/compose': typeof AppComposeRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/inspiration': typeof AppInspirationRoute
  '/profile': typeof AppProfileRoute
  '/feed/$storyId': typeof AppFeedStoryIdRoute
  '/feed/': typeof AppFeedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/compose': typeof AppComposeRoute
  '/inspiration': typeof AppInspirationRoute
  '/profile': typeof AppProfileRoute
  '/feed/$storyId': typeof AppFeedStoryIdRoute
  '/feed': typeof AppFeedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/compose': typeof AppComposeRoute
  '/_app/feed': typeof AppFeedRouteWithChildren
  '/_app/inspiration': typeof AppInspirationRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/feed/$storyId': typeof AppFeedStoryIdRoute
  '/_app/feed/': typeof AppFeedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/compose'
    | '/feed'
    | '/inspiration'
    | '/profile'
    | '/feed/$storyId'
    | '/feed/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/compose'
    | '/inspiration'
    | '/profile'
    | '/feed/$storyId'
    | '/feed'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/compose'
    | '/_app/feed'
    | '/_app/inspiration'
    | '/_app/profile'
    | '/_app/feed/$storyId'
    | '/_app/feed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspiration': {
      id: '/_app/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof AppInspirationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compose': {
      id: '/_app/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AppComposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed/': {
      id: '/_app/feed/'
      path: '/'
      fullPath: '/feed/'
      preLoaderRoute: typeof AppFeedIndexRouteImport
      parentRoute: typeof AppFeedRoute
    }
    '/_app/feed/$storyId': {
      id: '/_app/feed/$storyId'
      path: '/$storyId'
      fullPath: '/feed/$storyId'
      preLoaderRoute: typeof AppFeedStoryIdRouteImport
      parentRoute: typeof AppFeedRoute
    }
  }
}

interface AppFeedRouteChildren {
  AppFeedStoryIdRoute: typeof AppFeedStoryIdRoute
  AppFeedIndexRoute: typeof AppFeedIndexRoute
}

const AppFeedRouteChildren: AppFeedRouteChildren = {
  AppFeedStoryIdRoute: AppFeedStoryIdRoute,
  AppFeedIndexRoute: AppFeedIndexRoute,
}

const AppFeedRouteWithChildren =
  AppFeedRoute._addFileChildren(AppFeedRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppComposeRoute: typeof AppComposeRoute
  AppFeedRoute: typeof AppFeedRouteWithChildren
  AppInspirationRoute: typeof AppInspirationRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppComposeRoute: AppComposeRoute,
  AppFeedRoute: AppFeedRouteWithChildren,
  AppInspirationRoute: AppInspirationRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
